---
title: How to create a vocabulary list blog post
author: Brooke Anderson
date: '2020-02-04'
slug: creating-a-vocabulary-list-blog-post
categories:
  - instructions
  - vocabulary
  - blogdown
tags:
  - instructions
  - vocabulary
  - blogdown
subtitle: ''
summary: ''
authors: []
lastmod: '2020-02-03T10:37:52-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

As one of your assignments for this class, you are responsible for creating a blog
post with all the vocabulary and definitions for one week of the course. This 
blog post will explain how you can create and publish that blog post on our 
course website. 

# Create the blog post

## Update your fork of the website

You should have already forked our website to add your details for the "Person" 
section. You can use this same fork to add your blog post, but you should make sure
you get your fork up-to-date with the current version of the website before you do.

A fork of a repository does not stay up-to-date with the original repository it 
copied by itself. Instead, unless you update it, it will continue to be a snapshot
of the original repository (plus any changes you've made to your copy) as of 
the time when you forked it. If the original has made a lot of changes since you 
made your fork, it might be very hard to make a clean pull request as there will 
be (potentially) lots of conflicts because of changes made to the original. It's 
considered polite to make sure that you're working with an up-to-date fork of 
a repository if you want to make a pull request back to the original. 

[Git code to update fork]

[Updating your local branch]

## Making a new blog post

In `blogdown`, each blog post is an RMarkdown document. The stuff at the very top
of the file (the YAML with details like the title and author) will look a bit 
different than plain RMarkdown files, but once you get into the body of the post, 
you should find that the rules are very similar to RMarkdown. 

You will be creating a blog post that will include a table with the vocabulary
list as well as a few other elements. There are a few ways you can add a new
blog post file in `blogdown`. You're welcome to use any method you'd like, but
if you're not sure where to start, this is one way.

Make sure that you have RStudio open to the project for our course's website. If you
do, you should see `csu_msmb` in the upper right hand corner of your RStudio session.
(If not, go to `File` -> `Open Project...` and navigate through your file directory
to your local version of our project directory and open the `csu_msmb.RProj` file there.)

Next, you can use an RStudio "Addin" to make a new blog post using a nice 
user interface. These Addins are all alternatives to things you could do with a 
function call in R, but the Addin often provides a more immediately user-friendly
interface for you to enter options. For example, the Addin for creating a blog post
does all the actions of a `blogdown` function called `new_post`, but instead of needing
to remember the parameter name to use for the author listing and the title and all that, 
you can just fill the information into a nice form and go from there. 

To find the new post Addin, on the menu at the top of your RStudio session 
go to `Tools` -> `Addins` -> `Browse Addins...`. Once you're there, you should see 
an option for "New Post". Click on this and then click the "Execute" button. 
A form should pop up with spaces for you to fill in the title, author, and some other
details. 

Fill this form out in the following way: 

- **Title:** This should be "Vocabulary for Chapter [x]", but with "[x]" replaced
with your chapter number. 
- **Author:** Make sure you put your name exactly as listed in the "People" section 
of the website. This will help the website generator connect this post with your 
user profile, so when someone reads it they'll get your picture and a link to 
find out more about you at the end of the post.
- **Date:** This is where you put the publication date of your blog post, and it
has a pretty cool feature. Even if you write your blog post earlier, the post 
will not be published on the blog *until* the date listed in this section. That means
that you can start writing your blog on one day but know that it won't show up online
until later. It also means you can start work on your blog, but a half-finished 
draft won't show up online until you get to the publication date. For right now, 
set the current date in this section, so that your blog post will show up locally as
you work on it, but later you'll actually change this date so that, when you submit
your pull request, your post won't show up until the faculty have had the chance to 
suggest some changes and for you to make any needed fixes.
- **Categories and tags:** For both the "Categories" and the "Tags", be sure to 
include `vocabulary` and `Chapter [x]` (with [x] replaced with your chapter's number).
These tags will let everyone on our website quickly find all the blog posts on your
chapter or all the vocabulary lists.
- **Format:** You have several choices for the type of file to use to write your 
blog post. Since we're going to be using some R code to make the table look pretty, 
you'll need to pick one of the options that allows for R code chunks, so that rules 
out plain Markdown. I recommend that you use ".Rmd". 

Once you make these entries, click the button labeled "Done". This creates an 
RMarkdown file for your blog post and opens it for you. All of the blog posts are
saved in a special place in our project's directory: in the `content` subdirectory, 
there's a subdirectory called `post` that contains both the RMarkdown files used to
write the posts and the output (an HTML file) that is created by the RMarkdown each
time you save the file. You might notice that they all have long file names---the 
file name for a blog post is a combinataion of its publication date and its 
"slug", which is some abbreviation of the original title. If you really want, you 
can change what the slug will be when you first create the blog post, but I don't 
think you really need to.

## Creating a new blog post



# Create the vocabulary list

## Identify the vocabulary terms you need to define

## Create a .tsv file with terms and definitions

## Adding R code to show the list in the post

## Creating and embedding a Quizlet app


# Submit the post

## Pushing your changes to your remote repo

## Submitting a pull request to the original repo

# Edit and re-submit the post based on faculty feedback

