---
title: Ex 2.6
author: Sarah Cooper
date: '2020-02-24'
slug: ex-2-6
categories: 
- exercise 2.6
- chapter 2
tags: 
- exercise 2.6
- chapter 2
subtitle: ''
summary: ''
authors: []
lastmod: '2020-02-24T21:16:10-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects:
---

#Choose your own prior for the parameters of the beta distribution. You can do this by sketching it here: https://jhubiostatistics.shinyapps.io/drawyourprior. Once you have set up a prior, re-analyse the data from Section 2.9.2, where we saw Y = 40 successes out of n = 300 trials. Compare your posterior distribution to the one we obtained in that section using a QQ-plot.

#In 2.9.2, we looked at finding the marginal distribution of Y. In this example they used an alpha of 50, a beta of 350, and an n of 300 to generate a y for a random sample of 10000 thetas 
rtheta = rbeta(100000, 50, 350)
y = vapply(rtheta, function(th) {
  rbinom(1, prob = th, size = 300)
}, numeric(1))
hist(y, breaks = 50, col = "orange", main = "", xlab = "")

#After running the above, for each of these thetas, we then generate a random sample of Y as observed in this histogram (with orange bars).

#Our next step is to use this information to generate a posterior distribution of theta at a fixed Y value. In this example they used Y=40

thetaPostEmp = rtheta[ y == 40 ]
hist(thetaPostEmp, breaks = 40, col = "chartreuse4", main = "",
  probability = TRUE, xlab = expression("posterior"~theta))
densPostTheory  =  dbeta(thetas, 90, 610)
lines(thetas, densPostTheory, type="l", lwd = 3)

#After running the above, for each of these thetas, we generated simulated values for the posterior distribution of theta at Y=40 as observed in this histogram (with green bars).


#
mean(thetaPostEmp)
#0.1286394
dtheta = thetas[2]-thetas[1]
sum(thetas * densPostTheory * dtheta)
#0.1285714
#

#
qqplot(thetaPostMC, thetaPostEmp, type = "l", asp = 1)
abline(a = 0, b = 1, col = "blue")
#


